services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5500
      - MONGO_URL=mongodb+srv://Henil2202:Henil123@myatlasclusteredu.irzcbfs.mongodb.net/e-commerce
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
